### PR TITLE
query field to support Bulk V2

### PR DESCRIPTION
**Pull request by ashitsalesforce**

### CODE REVIEW

**Review by mgrumbach — COMMENTED** [review]
The JobInfo(Builder) constructur at line 43 needs an additional line to handle "query".

**Review by mgrumbach — COMMENTED** [review]
The loadFields() method contains a typo at line 657: it should call "setQuery()", but currently it calls "setObject()" which is wrong.

**Comment by ashitsalesforce** [comment]
Hi @mgrumbach, I have updated the PR based on your review feedback. Please review and let me know if the changes look good.

**Review by mgrumbach — COMMENTED** [review]
Please drop the .DS_STORE file from your commit.

**Pull request merged**
